version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Open this in your browser for the Jaeger UI
      - "4317:4317"   # OTLP gRPC Ingestion Port
      - "4318:4318"   # OTLP HTTP Ingestion Port (Used by Spring Boot)